#pragma once

#define I2C_ADDRESS 0x3C

#define STEPS_PER_REVOLUTION 200
#define STEPPER_MOTOR_ACCELERATION 50
#define STEPPER_MOTOR_DECELERATION 50
#define STEPPER_MOTOR_MICROSTEPS 16
#define STEPPER_MOTOR_RPM 15

#define STEPPER_DRIVER_DIR_PIN 12
#define STEPPER_DRIVER_STEP_PIN 14
#define BUTTON_PIN 27
